src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FilmRepository::class)
 */
class Film
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $film_id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $title;

    /**
     * @ORM\Column(type="decimal", precision=4, scale=2)
     */
    private $rental_rate;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $rating;

    /**
     * @ORM\Column(type="decimal", precision=4, scale=2)
     */
    private $rental_duration;

    public function getFilmId(): ?int
    {
        return $this->film_id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getRentalRate(): ?string
    {
        return $this->rental_rate;
    }

    public function setRentalRate(string $rental_rate): self
    {
        $this->rental_rate = $rental_rate;

        return $this;
    }

    public function getRating(): ?string
    {
        return $this->rating;
    }

    public function setRating(string $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getRentalDuration(): ?string
    {
        return $this->rental_duration;
    }

    public function setRentalDuration(string $rental_duration): self
    {
        $this->rental_duration = $rental_duration;

        return $this;
    }
}

src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Film;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('rental_rate')
            ->add('rating')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Film::class,
        ]);
    }
}

src/Controller/FilmController.php
<?php

namespace App\Controller;

use App\Entity\Film;
use App\Form\FilmType;
use App\Repository\FilmCategoryRepository;
use App\Repository\FilmRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/film")
 */
class FilmController extends AbstractController
{
    /**
     * @Route("/", name="film_index", methods={"GET"})
     */
    public function index(FilmRepository $filmRepository,PaginatorInterface $paginator, Request $request): Response
    {
        $donnees = $filmRepository->findAll();
        $film = $paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),10

        );
        return $this->render('film/index.html.twig', [
            'films' => $film,
        ]);
    }

    /**
     * @Route("/titleASC", name="film_title_asc", methods={"GET"})
     */
    public function sortTitleASC(FilmRepository $filmRepository,PaginatorInterface $paginator, Request $request): Response
    {
        $donnees = $filmRepository->sortASCFilm();
        $film = $paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),10

        );
        return $this->render('film/index.html.twig', [
            'films' => $film,
        ]);
    }

    /**
     * @Route("/titleDESC", name="film_title_desc", methods={"GET"})
     */
    public function sortTitleDESC(FilmRepository $filmRepository,PaginatorInterface $paginator, Request $request): Response
    {
        $donnees = $filmRepository->sortDESCFilm();
        $film = $paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),10

        );
        return $this->render('film/index.html.twig', [
            'films' => $film,
        ]);
    }

    /**
     * @Route("/rentalASC", name="film_rental_asc", methods={"GET"})
     */
    public function sortRentalASC(FilmRepository $filmRepository,PaginatorInterface $paginator, Request $request): Response
    {
        $donnees = $filmRepository->sortASCRental();
        $film = $paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),10

        );
        return $this->render('film/index.html.twig', [
            'films' => $film,
        ]);
    }

    /**
     * @Route("/rentalDESC", name="film_rental_desc", methods={"GET"})
     */
    public function sortRentalDESC(FilmRepository $filmRepository,PaginatorInterface $paginator, Request $request): Response
    {
        $donnees = $filmRepository->sortDESCRental();
        $film = $paginator->paginate(
            $donnees,
            $request->query->getInt('page',1),10

        );
        return $this->render('film/index.html.twig', [
            'films' => $film,
        ]);
    }


    /**
     * @Route("/new", name="film_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $film = new Film();
        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($film);
            $entityManager->flush();

            return $this->redirectToRoute('film_index');
        }

        return $this->render('film/new.html.twig', [
            'film' => $film,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="film_show", methods={"GET"})
     */
    public function show(Film $film): Response
    {
        return $this->render('film/show.html.twig', [
            'film' => $film,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="film_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Film $film): Response
    {
        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('film_index');
        }

        return $this->render('film/edit.html.twig', [
            'film' => $film,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="film_delete", methods={"POST"})
     */
    public function delete(Request $request, Film $film): Response
    {
        if ($this->isCsrfTokenValid('delete'.$film->getFilmId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($film);
            $entityManager->flush();
        }

        return $this->redirectToRoute('film_index');
    }
}

templates/film/_delete_form.html.twig
<form method="post" action="{{ path('film_delete', {'id': film.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ film.id) }}">
    <button class="btn">Delete</button>
</form>

templates/film/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/film/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Film{% endblock %}

{% block body %}
    <h1>Edit Film</h1>

    {{ include('film/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('film_index') }}">back to list</a>

    {{ include('film/_delete_form.html.twig') }}
{% endblock %}

templates/film/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film index{% endblock %}

{% block body %}
    <h1>Film index</h1>
    <p>Filtrer :</p>
    <p>Nom du film : <a href="{{ path('film_title_asc') }}">Ordre Croissant</a>   <a href="{{ path('film_title_desc')}}">Ordre Décroissant</a></p><br>
    <p>Genre du film : <a>Ordre Croissant</a>   <a>Ordre Décroissant</a></p><br>
    <p>Nombre de location : <a href="{{ path('film_rental_asc') }}">Ordre Croissant</a>   <a href="{{ path('film_rental_desc') }}">Ordre Décroissant</a></p><br>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Rental_rate</th>
                <th>Rental_duration</th>
                <th>Rating</th>
            </tr>
        </thead>
        <tbody>
        {% for film in films %}
            <tr>
                <td>{{ film.filmId }}</td>
                <td>{{ film.title }}</td>
                <td>{{ film.rentalRate }}</td>
                <td>{{ film.rentalDuration }}</td>
                <td>{{ film.rating }}</td>
              
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {{knp_pagination_render(films)}}

{% endblock %}

templates/film/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Film{% endblock %}

{% block body %}
    <h1>Create new Film</h1>

    {{ include('film/_form.html.twig') }}

    <a href="{{ path('film_index') }}">back to list</a>
{% endblock %}

templates/film/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film{% endblock %}

{% block body %}
    <h1>Film</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ film.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ film.title }}</td>
            </tr>
            <tr>
                <th>Rental_rate</th>
                <td>{{ film.rentalRate }}</td>
            </tr>
            <tr>
                <th>Rating</th>
                <td>{{ film.rating }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('film_index') }}">back to list</a>

    <a href="{{ path('film_edit', {'id': film.id}) }}">edit</a>

    {{ include('film/_delete_form.html.twig') }}
{% endblock %}